version: "2"
services:
  vficate-api:
    build: .
    environment:
      - MONGO_URI=mongodb://127.0.0.1/vficate-rest-express-app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
